### ISSUE TITLE
Island Utils 1.7.0 Tracking Issue

### ISSUE THREAD

**Issue by AsoDesu** [AsoDesu/IslandUtils#160]
- [x] Update to 1.21.3
   - [ ] Update to 1.21.4 when noxesium updates
 - [x] Fix Latest Noxesium support (#156)
 - [x] Fishing
   - [x] Add discord presence
   - [x] ~~Look into any features which can be added for rank perks~~ (there are none atm)
   - [x] Add icons to perks you can upgrade in fishing perks menu
- [x] Music
  - [x] Remove most of the music
  - [x] Update music modifiers (TGTTOS maps, double time & classic HITW) to work with island music
  - [x] Add music modifier for the previously used dynaball music
  - [x] ~~Fix music sliders to work with island music~~ (island has a music slider now)
  - [x] #163
- [x] Cosmetic Previews
  - [x] Add cosmetic previews for rods
  - [x] Debug some reported issues

**Comment by derNiklaas** [comment]
Here's a list of all fishing islands & grottos internal noxesium packet name.
The serverType is `lobby` and the subtype is one of the internal names below.
```kotlin
    /* Fishing Islands & Grottos */
    const val VERDANT_WOODS = "temperate_1"
    const val FLORAL_FOREST = "temperate_2"
    const val DARK_GROVE = "temperate_3"
    const val SUNKEN_SWAMP = "temperate_grotto"

    const val TROPICAL_OVERGROWTH = "tropical_1"
    const val CORAL_SHORES = "tropical_2"
    const val TWISTED_SWAMP = "tropical_3"
    const val MIRRORED_OASIS = "tropical_grotto"

    const val ANCIENT_SANDS = "barren_1"
    const val BLAZING_CANYON = "barren_2"
    const val ASHEN_WASTES = "barren_3"
    const val VOLCANIC_SPRINGS = "barren_grotto"
```

**Comment by thehamish555** [comment]
>  Update to 1.21.3

Will this also support 1.21 - 1.21.2? Would be great if it did!

**Comment by AsoDesu** [comment]
unfortunately no, i understand a lot of people are still on 1.21-1.21.2, but at the moment i'm focusing on: updating islandutils to the latest minecraft version, fixing bugs & adding support for new features. 
i've been working on 1.21.3 (as that was the latest version at the time of starting this update) and i will release a 1.21.4 version as well. but backporting changes takes A LOT of work

so the next island utils update will come out for 1.21.3 & 1.21.4
if anyone knows fabric and would be interested in backporting island utils for older versions, i would be more than happy to accept older-version branches as contributions!
